### PR TITLE
feat: add meta tags

### PR DESCRIPTION
**Pull request by raulwwq0**
| Is Bugfix | Related issues | Closes |
| --------- | -------------- | ------ |
| Yes/No    |  Add meta tags #3  |        |

### CODE REVIEW

**Comment by raulwwq0** [comment]
Since I have no info about what meta tags do you need, I add some of the most common ones. And also add add the title tag.

**Review by virtual-designer — CHANGES_REQUESTED** [review]
Everything looks cool 👍 ! Just remove the `title` tag, because nextjs complains about using the title tag in `_document.js`, it tells not to do that.

**Review by virtual-designer — CHANGES_REQUESTED** [review]
Everything looks cool 👍 ! Just remove the `title` tag, because nextjs complains about using the title tag in `_document.js`, it tells not to do that.

**Comment by raulwwq0** [comment]
Understood, I will remove the title tag.

**Review by virtual-designer — APPROVED** [review]
Cool 👍🏻

**Comment by virtual-designer** [comment]
Thanks for contributing!

**Comment by raulwwq0** [comment]
You're welcome, glad I could help :D

**Pull request merged**
