### PR TITLE
sticky header

### PR DESCRIPTION
**Pull request by arya312**
Changes made make the Navbar sticky for the Contact and the About pages.

### CODE REVIEW

**Review by virtual-designer — CHANGES_REQUESTED** [review]
Why `position: sticky;` to `*` aka all elements? This does not make sense. Instead, add some tailwindcss classes to [`Navbar.js`](https://github.com/onesoft-sudo/tes-website/blob/main/frontend/src/components/Navbar.js) component.

**Comment by arya312** [comment]
> Why `position: sticky;` to `*` aka all elements? This does not make sense. Instead, add some tailwindcss classes to [`Navbar.js`](https://github.com/onesoft-sudo/tes-website/blob/main/frontend/src/components/Navbar.js) component.

Sure, doing that right away!

**Review by virtual-designer — COMMENTED** [review]
Another thing, it's better to make multiple pull requests for different fixes or features. For example in this case, you should have made a new pull request for the footer fixes.

**Comment by arya312** [comment]
> Another thing, it's better to make multiple pull requests for different fixes or features. For example in this case, you should have made a new pull request for the footer fixes.

Could you please help me with how I should go about it. I thought this was a new pull request?

**Comment by virtual-designer** [comment]
> > Another thing, it's better to make multiple pull requests for different fixes or features. For example in this case, you should have made a new pull request for the footer fixes.
> 
> Could you please help me with how I should go about it. I thought this was a new pull request?

You can simply create a new branch and start modifying footer. Then when it's done, create a pull request from that branch. 

For now you've commited the changes already, so no need worry 😄 but create a new pull request from next time to work on different featurs/fixes.

**Comment by arya312** [comment]
> > > Another thing, it's better to make multiple pull requests for different fixes or features. For example in this case, you should have made a new pull request for the footer fixes.
> > 
> > 
> > Could you please help me with how I should go about it. I thought this was a new pull request?
> 
> You can simply create a new branch and start modifying footer. Then when it's done, create a pull request from that branch.
> 
> For now you've commited the changes already, so no need worry 😄 but create a new pull request from next time to work on different featurs/fixes.

Ohh okay, gotcha! Thanks, will do that the next time :)

**Comment by virtual-designer** [comment]
> > > > Another thing, it's better to make multiple pull requests for different fixes or features. For example in this case, you should have made a new pull request for the footer fixes.
> > > 
> > > 
> > > Could you please help me with how I should go about it. I thought this was a new pull request?
> > 
> > 
> > You can simply create a new branch and start modifying footer. Then when it's done, create a pull request from that branch.
> > For now you've commited the changes already, so no need worry 😄 but create a new pull request from next time to work on different featurs/fixes.
> 
> Ohh okay, gotcha! Thanks, will do that the next time :)

👍🏻

**Comment by arya312** [comment]
> You could've made a new PR for the contact page improvement as I said before

This is getting a little confusing for me 😅

I thought I had created a new pull request, which I probably did wrongly. So sorry for the inconvenience! I'll try to see what I can do.

**Comment by virtual-designer** [comment]
> > You could've made a new PR for the contact page improvement as I said before
> 
> This is getting a little confusing for me 😅
> 
> I thought I had created a new pull request, which I probably did wrongly. So sorry for the inconvenience! I'll try to see what I can do.

Oh okay, no problem. If you've finished working on the contact page, I think we should get these things merged first before making any new changes.

**Comment by arya312** [comment]
> > > You could've made a new PR for the contact page improvement as I said before
> > 
> > 
> > This is getting a little confusing for me 😅
> > I thought I had created a new pull request, which I probably did wrongly. So sorry for the inconvenience! I'll try to see what I can do.
> 
> Oh okay, no problem. If you've finished working on the contact page, I think we should get these things merged first before making any new changes.

Yes, I've finished working on the contact page!

**Comment by virtual-designer** [comment]
I've merged this, but for some reason I had to refactor the whole frontend into plain react application. The other PRs have merge conflicts and stuff, so I'm closing them for now.

**Pull request merged**
